// <auto-generated />
using System;
using HS_Feed_Manager.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

// ReSharper disable All

namespace HS_Feed_Manager.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("HS_Feed_Manager.DataModels.DbModels.Episode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DownloadDate");

                    b.Property<double>("EpisodeNumber");

                    b.Property<string>("Link");

                    b.Property<string>("LocalPath");

                    b.Property<string>("Name");

                    b.Property<int>("Rating");

                    b.Property<int>("TvShowId");

                    b.HasKey("Id");

                    b.HasIndex("TvShowId");

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("HS_Feed_Manager.DataModels.DbModels.TvShow", b =>
                {
                    b.Property<int>("TvShowId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AutoDownloadStatus");

                    b.Property<int>("EpisodeCount");

                    b.Property<DateTime>("LatestDownload");

                    b.Property<int>("LocalEpisodesCount");

                    b.Property<string>("Name");

                    b.Property<int>("Rating");

                    b.Property<int>("Status");

                    b.HasKey("TvShowId");

                    b.ToTable("TvShows");
                });

            modelBuilder.Entity("HS_Feed_Manager.DataModels.DbModels.Episode", b =>
                {
                    b.HasOne("HS_Feed_Manager.DataModels.DbModels.TvShow", "TvShow")
                        .WithMany("Episodes")
                        .HasForeignKey("TvShowId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
